### ISSUE TITLE
Gemname should change

### ISSUE THREAD

**Issue by HoneyryderChuck** [goncalossilva/acts_as_paranoid#79] opened 2012-09-24 09:05 UTC
Hi,

I have an issue with the name. Currently I am bundling a Sinatra Gem with AR3, and I need my models to be paranoid. And this gem has been doing the gem. Granted, it's still not deployed, maybe I'm forgetting some dependency. But if all goes well and it indeed all runs well, I don't see why I have to have a gem rails3-prefixed in a sinatra app. I can see the issues with the renaming (projects depending on it, etc.) but I'd say it'd be more consistent. Please tell me what u think.

Regards
Tiago

**Comment by chuckg** [comment] 2012-10-11 21:02
Your suggestion makes total sense, Tiago. Is your suggestion that the name be changed to "activerecord_acts_as_paranoid"? Definitely more clear, but perhaps a question best answered by the gem's original owner, @goncalossilva.

**Comment by goncalossilva** [comment] 2012-10-12 03:10
+1

What do you think we should do regarding rubygems? Just link the new version?

**Comment by HoneyryderChuck** [comment] 2012-10-13 08:51
Well, since the gem is only for activerecord, I'd call it "ar_acts_as_paranoid", "ar_paranoid", a variation of the concept. I also don't know if you plan to extend the functionality to mongoid or DM ORMs, for which then the name would become also wrong (then only "acts_as_paranoid" would make sense, even though it might still be taken). 

Regarding rubygems, I don't know if it is possible to "redirect" the rails3-prefixed to a new one. I'd have to investigate the possibilities. But I guess this would not be the first gem to try to make a name leap. 

I don't know what the first step should be. But if you'd ask me, I would try to kick this https://github.com/technoweenie/acts_as_paranoid butt out of the github system, and then take over the name in good old middle age fashion :)

**Comment by goncalossilva** [comment] 2012-10-19 16:36
Naming it "acts_as_paranoid" makes more sense to me. The problem is findability, most people come across this gem because they search for "acts_as_paranoid rails3" or something similar.

I could ping @technoweenie and ask him to mention this gem for Rails 3, though.

What do you think, @chuckg?

**Comment by chuckg** [comment] 2012-10-19 16:47
Another option is to keep this project up as a redirect to the new project.
Whether it redirects to an "acts_as_paranoid" (pending approval from
technoweenie) or "ar3_acts_as_paranoid" is up to you.  I'm of the opinion
that taking over the "acts_as_paranoid" name is the best solution. Releases
for different Rails versions are archive by rubygems (I think), so
maintaining a single master going forward against the latest stable version
of ActiveRecord makes the most sense to me.

Then again, keeping it as rails3_acts_as_paranoid is fine. When Rails 4
comes out, you just make a new project and the problem is solved; hello
"rails4_acts_as_paranoid".

All that probably doesn't help your decision much, does it? :)

**Comment by goncalossilva** [comment] 2012-10-19 17:06
I agree that "acts_as_paranoid" is the best way to go. We (mainteners) just need to have the responsability of admiting that we won't always be available and encourage/accept PR and promote new maintainers from time to time to keep the wheels running while new AR versions come out.

I'll ping @technoweenie on Twitter.

**Comment by technoweenie** [comment] 2012-10-20 14:04
You guys can have the gem name if you want.  Just let me know who the new
owners are, and I'll give them access to
http://rubygems.org/gems/acts_as_paranoid

**Comment by goncalossilva** [comment] 2012-10-20 14:09
@technoweenie thanks!

Chuck and I are currently maintaining this gem. My email is goncalossilva at gmail.

**Comment by technoweenie** [comment] 2012-10-20 22:32
All set!

**Comment by HoneyryderChuck** [comment] 2012-10-21 22:31
Sorry for the late reply. acts_as_paranoid is the solution, my +1 on that. About keeping the name and using the same variant for rails 4, I think you can do as well by versioning, as most gems do. And it's still very out in the open whether great changes will be introduced for the AR4 version as there where from the rails2 to 3 jump.

**Comment by goncalossilva** [comment] 2012-10-22 06:50
@TiagoCardoso1983 yeah, I'll do that.

Thanks again, @technoweenie!

The current acts_as_paranoid gem is at 0.3.1. I think we could make the following releases:
0.8 -> our current 3.0 release
0.9 -> our current 3.1 release
1.0 -> our current 3.2 release

When Rails 4 comes out we just move to 1.1 (or 2.0).

I'll make the necessary changes over this week.

**Comment by f3ndot** [comment] 2013-01-11 20:37
I'd like to point out that the bundle post-install message from `rails3_acts_as_paranoid` shows:

```
Post-install message from rails3_acts_as_paranoid:

=======================================

  This gem has moved!

  To stay up to date, run:

    $ gem install 'acts_as_paranoid'"

=======================================
```

But the gem `acts_as_paranoid` is clearly the old version from 2011... What gives?

**Comment by goncalossilva** [comment] 2013-01-11 20:42
That's expected :)

If you install ~>0.4, it the current version.

**Comment by zzak** [comment] 2014-05-12 18:41
Marking this as resolved, we already have 1 gem which is developed here.

**Closed as completed by zzak** 2014-05-12 18:41 UTC
