### ISSUE TITLE
Cannot destroy object if the model has default_scope with reference to another table

### ISSUE THREAD

**Issue by mitoyarzun** [goncalossilva/acts_as_paranoid#111] opened 2013-05-10 15:59 UTC
How to reproduce:

``` ruby
class Parent < ActiveRecord::Base
  acts_as_paranoid
  has_many :children
end

class Child < ActiveRecord::Base
  belongs_to :parent
  acts_as_paranoid
  default_scope includes(:parent).order('parents.position DESC')
end

```

When you try to destroy a Child, it can't because the default scope is not called:

```
ActiveRecord::StatementInvalid: Mysql2::Error: Unknown column 'parents.position' in 'order clause': UPDATE `children` SET deleted_at = '2013-05-10 15:41:09' WHERE `children`.`id` = 5 ORDER BY parents.position ASC
```

Can anyone reproduce it?

Thanks.

**Comment by alexisraca** [comment] 2013-09-10 21:06
- 1 to this, error on PG, it says the refference does not exist when it tries to reorder, is there a workaround?

**Comment by zzak** [comment] 2014-05-12 23:26
I think this is a duplicate of #62

**Closed as completed by zzak** 2014-05-12 23:26 UTC
